import "./globals.css";
import { Inter } from "next/font/google";
import { Nav } from "./component";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);

  const cookie = cookies().get("isDark");
  const boolean =
    cookie === undefined ? false : cookie.value === "true" ? true : false;
  console.log("레이아웃쿠키 isDark?", boolean);

  return (
    <html lang="en">
      <body
        className={
          inter.className + `${boolean ? " bg-gray-700" : " bg-white"}`
        }
      >
        <Nav
          username={session === null ? null : session.user.username}
          user={session === null ? false : true}
          userimg={session === null ? null : session.user.image}
          layoutCookie={boolean}
        />
        {children}
      </body>
    </html>
  );
}
